# Generated by Django 5.1.3 on 2025-02-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ontime',
            field=models.TimeField(null=True),
        ),
    ]
